server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: rentalmain

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:mysql://${DB_HOST:db}:${DB_PORT:3306}/${DB_NAME:rentalMain}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: ${HIBERNATE_FORMAT_SQL:true}

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  task:
    execution:
      pool:
        core-size: 2
        max-size: 5

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info,metrics,prometheus,mappings}
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:always}
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: ${LOG_LEVEL_ROOT:info}
    com.xpro.rentalmain: ${LOG_LEVEL_APP:debug}
    org.springframework.web: ${LOG_LEVEL_WEB:debug}
    org.springframework.security: ${LOG_LEVEL_SECURITY:debug}
    org.springframework.orm.jpa: ${LOG_LEVEL_JPA:debug}
    org.hibernate.orm.jdbc.bind: ${LOG_LEVEL_HIBERNATE_BIND:trace}

app:
  security:
    system-secret: ${SYSTEM_SECRET}
    jwt:
      secret: ${SYSTEM_SECRET}
      expiration: ${JWT_EXPIRATION:9000000}